# Users
users = [
    {
        "username": "clarice",
        "first_name": "Clarice",
        "last_name": "Lispector",
        "date_of_birth": "2012-06-22",
        "customer_tier": "PLATINUM",
    },
    {
        "username": "adam",
        "first_name": "Adam",
        "last_name": "Barbosa",
        "date_of_birth": "1990-03-22",
        "customer_tier": "SILVER",
    },
    {
        "username": "megan",
        "first_name": "Megan",
        "last_name": "Margarida",
        "date_of_birth": "1992-11-30",
        "customer_tier": "GOLD",
    },
    {
        "username": "hemal",
        "first_name": "Hemal",
        "last_name": "Oliveira",
        "date_of_birth": "1977-08-05",
        "customer_tier": "BRONZE",
    },
    {
        "username": "siri",
        "first_name": "Siri",
        "last_name": "Pereira",
        "date_of_birth": "1974-01-18",
        "customer_tier": "BLUE",
    },
]

# Products
products = [
    {
        "product_id": "P001",
        "name": "Running Trainers",
        "category": "Footwear",
        "price": 89.99,
        "description": "Lightweight running shoes with responsive cushioning for long-distance comfort.",
        "icon": "👟",
    },
    {
        "product_id": "P002",
        "name": "Yoga Mat",
        "category": "Sports & Fitness",
        "price": 29.99,
        "description": "Non-slip yoga mat with extra cushioning for comfort during practice.",
        "icon": "🧘",
    },
    {
        "product_id": "P003",
        "name": "Water Bottle",
        "category": "Accessories",
        "price": 19.99,
        "description": "Insulated stainless steel bottle keeps drinks cold for 24 hours.",
        "icon": "💧",
    },
    {
        "product_id": "P004",
        "name": "Running Shorts",
        "category": "Apparel",
        "price": 34.99,
        "description": "Breathable running shorts with moisture-wicking fabric and zippered pocket.",
        "icon": "🩳",
    },
    {
        "product_id": "P005",
        "name": "Sports Watch",
        "category": "Electronics",
        "price": 199.99,
        "description": "GPS-enabled sports watch with heart rate monitoring and activity tracking.",
        "icon": "⌚",
    },
    {
        "product_id": "P006",
        "name": "Gym Bag",
        "category": "Accessories",
        "price": 49.99,
        "description": "Spacious gym bag with separate shoe compartment and water bottle holder.",
        "icon": "🎒",
    },
    {
        "product_id": "P007",
        "name": "Resistance Bands",
        "category": "Sports & Fitness",
        "price": 24.99,
        "description": "Set of 5 resistance bands for strength training and stretching exercises.",
        "icon": "🏋️",
    },
    {
        "product_id": "P008",
        "name": "Track Jacket",
        "category": "Apparel",
        "price": 74.99,
        "description": "Lightweight track jacket with wind-resistant fabric and reflective details.",
        "icon": "🧥",
    },
    {
        "product_id": "P009",
        "name": "Protein Shaker",
        "category": "Accessories",
        "price": 14.99,
        "description": "Leak-proof protein shaker with mixing ball and measurement markings.",
        "icon": "🥤",
    },
    {
        "product_id": "P010",
        "name": "Wireless Earbuds",
        "category": "Electronics",
        "price": 129.99,
        "description": "Sweat-resistant wireless earbuds with noise cancellation and 8-hour battery.",
        "icon": "🎧",
    },
    {
        "product_id": "P011",
        "name": "Badminton Racket",
        "category": "Sports & Fitness",
        "price": 119.99,
        "description": "Carbon fiber badminton racket with enhanced control and power.",
        "icon": "🏸",
    },
    {
        "product_id": "P012",
        "name": "Cycling Helmet",
        "category": "Sports & Fitness",
        "price": 59.99,
        "description": "Adjustable cycling helmet with MIPS technology for enhanced safety.",
        "icon": "🚴",
    },
    {
        "product_id": "P013",
        "name": "Swimming Goggles",
        "category": "Sports & Fitness",
        "price": 24.99,
        "description": "Anti-fog swimming goggles with UV protection and adjustable straps.",
        "icon": "🥽",
    },
    {
        "product_id": "P014",
        "name": "Basketball",
        "category": "Sports & Fitness",
        "price": 39.99,
        "description": "Official size basketball with superior grip for indoor and outdoor play.",
        "icon": "🏀",
    },
    {
        "product_id": "P015",
        "name": "Dumbbell Set",
        "category": "Sports & Fitness",
        "price": 79.99,
        "description": "Adjustable dumbbell set with weights from 5kg to 25kg per hand.",
        "icon": "🏋️",
    },
    {
        "product_id": "P016",
        "name": "Ski Goggles",
        "category": "Sports & Fitness",
        "price": 89.99,
        "description": "Anti-fog ski goggles with UV protection and interchangeable lenses.",
        "icon": "⛷️",
    },
    {
        "product_id": "P017",
        "name": "Football",
        "category": "Sports & Fitness",
        "price": 29.99,
        "description": "Premium leather football with superior touch and durability.",
        "icon": "⚽",
    },
    {
        "product_id": "P018",
        "name": "Hiking Boots",
        "category": "Footwear",
        "price": 149.99,
        "description": "Waterproof hiking boots with ankle support and rugged traction.",
        "icon": "🥾",
    },
    {
        "product_id": "P019",
        "name": "Fitness Tracker",
        "category": "Electronics",
        "price": 99.99,
        "description": "Advanced fitness tracker with sleep monitoring and smartphone notifications.",
        "icon": "📱",
    },
    {
        "product_id": "P020",
        "name": "Boxing Gloves",
        "category": "Sports & Fitness",
        "price": 54.99,
        "description": "Padded boxing gloves with wrist support for training and sparring.",
        "icon": "🥊",
    },
    {
        "product_id": "P021",
        "name": "Yoga Blocks",
        "category": "Sports & Fitness",
        "price": 19.99,
        "description": "Set of 2 lightweight foam blocks for yoga poses and stretching support.",
        "icon": "🧱",
    },
    {
        "product_id": "P022",
        "name": "Smart Air Purifier",
        "category": "Home",
        "price": 159.99,
        "description": "HEPA filter air purifier with smart controls and air quality monitoring.",
        "icon": "💨",
    },
    {
        "product_id": "P023",
        "name": "Robot Vacuum",
        "category": "Home",
        "price": 299.99,
        "description": "Smart robot vacuum with mapping technology and app control for effortless cleaning.",
        "icon": "🤖",
    },
]

# Stores
stores = [
    {
        "store_id": "S001",
        "name": "UrbanStreet Oxford Street",
        "location": "London, UK",
        "icon": "🏢",
        "promotions": [
            "Free coffee from opening until 12:00 PM (All tiers)",
            "5% discount for abandoned cart items (BRONZE+)",
            "Loyalty points double on weekends (SILVER+)",
            "Flash sale: 15% off running shoes today only (All tiers)",
            "Buy 2 get 1 free on yoga accessories (BRONZE+)",
            "VIP lounge access with complimentary snacks (GOLD+)",
            "Priority checkout lanes (PLATINUM)",
            "Spend $100 get $15 voucher for next visit (All tiers)",
        ],
    },
    {
        "store_id": "S002",
        "name": "UrbanStreet Manchester",
        "location": "Manchester, UK",
        "icon": "🏪",
        "promotions": [
            "Free coffee and pastries until 11:00 AM (All tiers)",
            "7% discount for abandoned cart items (SILVER+)",
            "Student discount: 10% off with valid ID (BRONZE+)",
            "Early bird special: 20% off before 10:00 AM (All tiers)",
            "Weekly deal: 25% off fitness equipment this week (BRONZE+)",
            "Personal shopping assistant (GOLD+)",
            "Free home delivery on purchases over $50 (PLATINUM)",
            "Spend $75 today get free water bottle (All tiers)",
        ],
    },
    {
        "store_id": "S003",
        "name": "UrbanStreet Birmingham",
        "location": "Birmingham, UK",
        "icon": "🏬",
        "promotions": [
            "Complimentary refreshments all day (SILVER+)",
            "4% discount for abandoned cart items (BRONZE+)",
            "Friday flash sale: up to 30% off selected items (All tiers)",
            "Bundle deal: Save 20% on 3+ items (BRONZE+)",
            "Clearance corner: up to 50% off (All tiers)",
            "Extended warranty on electronics (GOLD+)",
            "Free product customization service (PLATINUM)",
            "Spend $60 get $10 off next purchase (All tiers)",
        ],
    },
    {
        "store_id": "S004",
        "name": "UrbanStreet Glasgow",
        "location": "Glasgow, UK",
        "icon": "🏭",
        "promotions": [
            "Free coffee from opening until 1:00 PM (All tiers)",
            "10% discount for abandoned cart items (GOLD+)",
            "Early bird special: 15% off purchases before 10:00 AM (BRONZE+)",
            "Weekend promo: Buy one get one 50% off (All tiers)",
            "VIP members: extra 5% off all purchases (SILVER+)",
            "Trade-in old gear: get 15% off new items (BRONZE+)",
            "Exclusive early access to new products (PLATINUM)",
            "Spend $90 unlock free delivery on next online order (All tiers)",
        ],
    },
    {
        "store_id": "S005",
        "name": "UrbanStreet Reading",
        "location": "Reading, UK",
        "icon": "🏛️",
        "promotions": [
            "Free tea and coffee until 12:00 PM (All tiers)",
            "6% discount for abandoned cart items (SILVER+)",
            "Birthday month special: 15% off entire purchase (All tiers)",
            "Local loyalty: 8% off for Reading residents (BRONZE+)",
            "Midweek madness: 20% off Tuesdays and Wednesdays (All tiers)",
            "Family bundle: 25% off when buying for 2+ people (BRONZE+)",
            "Complimentary gift wrapping (GOLD+)",
            "Spend $80 enter prize draw for $500 gift card (All tiers)",
        ],
    },
]

# Partners
partners = [
    {
        "partner_id": "PTR001",
        "name": "ShopNow",
        "categories": {
            "Sports & Fitness": [
                "10% off sports equipment for SILVER+ members",
                "Free shipping on fitness gear orders over $50 (All tiers)",
                "Buy 2 get 15% off athletic wear (BRONZE+)",
                "Exclusive early access to new sports releases (GOLD+)",
            ],
            "Home": [
                "15% off home products (BRONZE+)",
                "Flash deal: 20% off home today only (All tiers)",
                "Loyalty bonus: Extra 5% off for PLATINUM members",
                "Bundle deal: Save 25% on 3+ home items (SILVER+)",
            ],
            "Apparel": [
                "Student discount: 12% off with valid ID (All tiers)",
                "VIP styling consultation for GOLD+ members",
                "Seasonal clearance: up to 40% off (All tiers)",
                "Birthday bonus: 20% off during your birthday month (BRONZE+)",
            ],
        },
        "icon": "🛍️",
    },
    {
        "partner_id": "PTR002",
        "name": "QuickDelivery",
        "categories": {
            "Electronics": [
                "Extended warranty included for PLATINUM members",
                "Same-day delivery on electronics (SILVER+)",
                "Trade-in bonus: $30 off when trading old devices (All tiers)",
                "Tech bundle: Save 18% on 2+ electronics (BRONZE+)",
            ],
            "Sports & Fitness": [
                "Free delivery on sports gear over $40 (All tiers)",
                "Weekend special: 15% off team sports equipment (BRONZE+)",
                "Price match guarantee plus 5% off (GOLD+)",
                "Refer a friend: Both get $10 off (All tiers)",
            ],
            "Home": [
                "Home essentials bundle: Save 20% (BRONZE+)",
                "Free assembly service for PLATINUM members",
                "Flash sale: 25% off home gym equipment (All tiers)",
                "Buy now, pay later available (SILVER+)",
            ],
        },
        "icon": "📦",
    },
    {
        "partner_id": "PTR003",
        "name": "MarketPlace",
        "categories": {
            "Footwear": [
                "Adventure bundle: 15% off hiking gear (All tiers)",
                "Seasonal clearance: up to 35% off camping equipment (BRONZE+)",
                "Expert advice session included for GOLD+ members",
                "Buy 3+ outdoor items get free waterproof bag (SILVER+)",
            ],
            "Sports & Fitness": [
                "Wellness Wednesday: 20% off supplements (All tiers)",
                "Free nutrition guide with purchase (BRONZE+)",
                "Subscribe & save: 15% off recurring orders (SILVER+)",
                "Premium health consultation for PLATINUM members",
            ],
            "Accessories": [
                "Mix & match: 3 for 2 on accessories (All tiers)",
                "Personalization service available for GOLD+ members",
                "First-time buyer: 15% off your first order (All tiers)",
                "Loyalty reward: Free accessory on 5th purchase (BRONZE+)",
            ],
        },
        "icon": "🌐",
    },
    {
        "partner_id": "PTR004",
        "name": "RetailHub",
        "categories": {
            "Electronics": [
                "Tech Tuesday: 15% off smart devices (All tiers)",
                "Free tech support for 1 year (GOLD+)",
                "Student discount: 18% off with valid ID (All tiers)",
                "Bundle & save: 22% off 2+ tech products (SILVER+)",
            ],
            "Sports & Fitness": [
                "Fitness challenge: 10% off + free meal plan (BRONZE+)",
                "Personal training discount: 30% off sessions (PLATINUM)",
                "Equipment upgrade: Trade-in old for 20% off new (All tiers)",
                "Group discount: 15% off for 3+ items (SILVER+)",
            ],
            "Apparel": [
                "Fashion Friday: 25% off selected apparel (All tiers)",
                "Size exchange guarantee for GOLD+ members",
                "Buy 2 get 1 half price on activewear (BRONZE+)",
                "Exclusive designer collaborations for PLATINUM members",
            ],
        },
        "icon": "🏬",
    },
]
